Ft-Create-Login-Page
TimeOfGift/letsmeet-frontend pull request #21
Opened 2021-11-03 10:30 UTC by Morsetim

https://trello.com/c/K2VeOgvY/21-login-page

2021-11-10 22:56 UTC, hnobi requested changes
Please the Login should look something like this below. 

<img width="1440" alt="Screenshot 2021-11-10 at 11 55 18 PM" src="https://user-images.githubusercontent.com/29021978/141206959-8b9fc8e0-3d4e-4c81-a014-d778ffe91c4f.png">

2021-11-10 22:56 UTC, hnobi commented on src/pages/SignIn/index.js
> +                <hr />
Please remove hr and make FormTitle `rectColor`

2021-11-10 22:56 UTC, hnobi commented on src/pages/SignIn/index.js
> +                <FormTitle text="Login" rectColor="none" className="form-title" textColor="black"/>
add a rectColor

2021-11-11 04:01 UTC, Morsetim commented on src/pages/SignIn/index.js
> +                <hr />
Oh I see, will be get it done as soon as possible

2021-11-11 04:01 UTC, Morsetim commented on src/pages/SignIn/index.js
> +                <FormTitle text="Login" rectColor="none" className="form-title" textColor="black"/>
Okay

2021-11-12 21:27 UTC, hnobi approved these changes

2021-11-12 21:27 UTC, merged